/**
 * GNECT — Push Schema to Turso
 *
 * This script pushes the Prisma schema to a Turso (libSQL) database.
 * It reads the SQL generated by `prisma migrate diff` and applies it.
 *
 * Usage:
 *   DATABASE_URL=libsql://your-db.turso.io DATABASE_AUTH_TOKEN=your-token bun run scripts/push-to-turso.ts
 *
 * Or set these in your .env file.
 */
import { createClient, type Client } from '@libsql/client'
import { readFileSync } from 'fs'

const TURSO_URL = process.env.DATABASE_URL || ''
const TURSO_TOKEN = process.env.DATABASE_AUTH_TOKEN || ''

if (!TURSO_URL.startsWith('libsql://') && !TURSO_URL.startsWith('https://')) {
  console.error('❌ DATABASE_URL must start with libsql:// or https://')
  console.error('   Set it in .env or pass as environment variable')
  process.exit(1)
}

if (!TURSO_TOKEN) {
  console.error('❌ DATABASE_AUTH_TOKEN is required')
  process.exit(1)
}

const libsql: Client = createClient({
  url: TURSO_URL,
  authToken: TURSO_TOKEN,
})

async function main() {
  console.log('🔄 Connecting to Turso...')

  // Test connection
  try {
    const tables = await libsql.execute("SELECT name FROM sqlite_master WHERE type='table'")
    console.log(`✅ Connected! Existing tables: ${tables.rows.map(r => r.name).join(', ') || 'none'}`)
  } catch (err: any) {
    console.error('❌ Connection failed:', err?.message)
    process.exit(1)
  }

  // Generate schema SQL using prisma
  const { execSync } = await import('child_process')
  let schemaSQL: string

  try {
    console.log('📋 Generating schema SQL from Prisma...')
    schemaSQL = execSync('npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script', {
      cwd: process.cwd(),
      encoding: 'utf-8',
    })
  } catch {
    console.error('❌ Failed to generate schema SQL. Falling back to cached file.')
    try {
      schemaSQL = readFileSync('/tmp/turso-schema.sql', 'utf-8')
    } catch {
      console.error('❌ No cached schema file found either.')
      process.exit(1)
    }
  }

  // Split into statements
  const statements = schemaSQL
    .split('\n')
    .filter(line => line.trim() && !line.trim().startsWith('--'))
    .join('\n')
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0)

  console.log(`📋 Executing ${statements.length} SQL statements...`)

  let success = 0
  let skipped = 0
  let failed = 0

  for (const stmt of statements) {
    try {
      await libsql.execute(stmt)
      success++
    } catch (err: any) {
      if (err?.message?.includes('already exists')) {
        skipped++
      } else {
        failed++
        console.error(`  ❌ Failed: ${stmt.substring(0, 80)}... — ${err?.message}`)
      }
    }
  }

  console.log(`\n📊 Results: ${success} created, ${skipped} skipped (already exists), ${failed} failed`)

  // Verify tables
  const result = await libsql.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
  console.log(`\n✅ Turso tables (${result.rows.length}):`)
  result.rows.forEach(r => console.log(`   - ${r.name}`))

  // Check indexes
  const idxResult = await libsql.execute("SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%' ORDER BY name")
  console.log(`\n✅ Turso indexes (${idxResult.rows.length}):`)
  idxResult.rows.forEach(r => console.log(`   - ${r.name}`))
}

main().catch(err => {
  console.error('Fatal error:', err)
  process.exit(1)
})
